# Visit 3.1.1 log file
ScriptVersion = "3.1.1"
if ScriptVersion != Version():
    print "This script is for VisIt %s. It may not work with version %s" % (ScriptVersion, Version())
visit.ShowAllWindows()
visit.SetActivePlots()
visit.DeleteActivePlots()
visit.OpenDatabase("/home/ddb/codes/afivo-pic/programs/dielectric_2d/output/test_*.silo database", 0)
# The UpdateDBPluginInfo RPC is not supported in the VisIt module so it will not be logged.
visit.AddPlot("Pseudocolor", "O_atom", 1, 1)
visit.DrawPlots()
visit.SetTimeSliderState(0)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(1)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(2)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(3)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(4)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(5)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(6)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(7)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(8)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(9)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(10)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(11)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(12)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(13)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(14)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(15)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(16)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(17)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(18)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(19)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(20)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(21)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(22)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(23)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(24)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(25)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(26)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(27)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(28)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(29)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(30)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(31)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(32)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(33)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(34)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(35)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(36)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(37)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(38)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(39)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(40)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(41)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(42)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(43)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(44)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(45)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(46)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(47)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(48)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(49)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(50)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(51)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(52)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(53)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(54)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(55)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(56)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(57)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(58)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(59)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(60)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(61)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(62)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(63)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(64)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(65)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(66)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(67)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(68)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(69)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(70)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(71)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(72)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(73)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(74)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(75)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(76)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(77)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(78)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(79)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(80)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(81)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(82)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(83)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(84)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(85)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(86)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(87)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(88)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(89)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(90)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(91)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(92)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(93)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(94)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(95)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(96)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(97)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(98)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(99)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(100)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(101)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(102)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(103)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(104)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(105)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(106)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(107)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(108)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(109)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(110)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(111)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(112)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(113)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(114)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(115)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(116)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(117)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(118)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(119)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(120)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(121)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(122)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(123)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(124)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(125)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(126)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(127)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(128)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(129)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(130)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(131)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(132)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(133)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(134)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(135)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(136)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(137)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(138)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(139)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(140)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(141)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(142)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(143)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(144)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(145)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(146)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(147)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(148)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(149)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(150)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(151)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(152)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(153)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(154)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(155)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(156)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(157)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(158)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(159)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(160)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(161)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(162)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(163)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(164)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(165)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(166)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(167)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(168)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(169)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(170)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(171)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(172)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(173)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(174)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(175)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(176)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(177)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(178)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(179)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(180)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(181)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(182)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(183)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(184)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(185)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(186)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(187)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(188)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(189)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(190)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(191)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(192)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(193)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(194)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(195)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(196)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(197)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(198)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(199)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(200)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(201)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(202)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(203)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(204)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(205)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(206)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(207)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(208)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(209)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(210)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(211)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(212)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(213)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(214)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(215)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(216)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(217)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(218)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(219)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(220)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(221)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(222)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(223)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(224)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(225)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(226)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(227)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(228)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(229)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(230)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(231)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(232)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(233)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(234)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(235)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(236)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(237)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(238)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(239)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(240)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(241)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(242)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(243)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(244)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(245)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(246)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(247)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(248)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(249)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(250)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(251)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(252)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(253)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(254)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(255)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(256)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(257)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(258)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(259)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(260)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(261)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(262)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(263)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(264)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(265)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(266)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(267)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(268)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(269)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(270)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(271)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(272)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(273)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(274)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(275)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(276)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(277)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(278)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(279)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(280)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(281)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(282)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(283)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(284)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(285)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(286)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(287)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(288)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(289)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(290)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(291)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(292)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(293)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(294)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(295)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(296)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(297)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(298)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(299)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(300)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(301)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(302)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(303)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(304)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(305)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(306)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(307)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(308)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(309)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(310)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(311)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(312)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(313)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(314)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(315)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(316)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(317)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(318)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(319)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
visit.SetTimeSliderState(320)
visit.Query("Weighted Variable Sum")
visit.Query("Time")
# Begin spontaneous state
View2DAtts = visit.View2DAttributes()
View2DAtts.windowCoords = (0, 0.003, 0, 0.01)
View2DAtts.viewportCoords = (0.2, 0.95, 0.15, 0.95)
View2DAtts.fullFrameActivationMode = View2DAtts.Auto  # On, Off, Auto
View2DAtts.fullFrameAutoThreshold = 100
View2DAtts.xScale = View2DAtts.LINEAR  # LINEAR, LOG
View2DAtts.yScale = View2DAtts.LINEAR  # LINEAR, LOG
View2DAtts.windowValid = 1
visit.SetView2D(View2DAtts)
# End spontaneous state

# Begin spontaneous state
View2DAtts = visit.View2DAttributes()
View2DAtts.windowCoords = (0, 0.003, 0, 0.01)
View2DAtts.viewportCoords = (0.2, 0.95, 0.15, 0.95)
View2DAtts.fullFrameActivationMode = View2DAtts.Auto  # On, Off, Auto
View2DAtts.fullFrameAutoThreshold = 100
View2DAtts.xScale = View2DAtts.LINEAR  # LINEAR, LOG
View2DAtts.yScale = View2DAtts.LINEAR  # LINEAR, LOG
View2DAtts.windowValid = 1
visit.SetView2D(View2DAtts)
# End spontaneous state

